converted to caching assets where the assets are always built in the slug and cached.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,7 +2,7 @@
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
 ### Configure environment
-
+echo "GIT_DIR: $GIT_DIR"
 set -o errexit    # always exit on error
 set -o pipefail   # don't ignore exit codes when piping output
 set -o nounset    # fail on unset variables
@@ -15,19 +15,20 @@ CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
 
-mkdir -p "$BUILD_DIR/.heroku/node/"
-cd $BUILD_DIR
-export PATH="$BUILD_DIR/.heroku/node/bin":$PATH
 
+cd $BUILD_DIR
+ls -la
+
+ls -la .profile.d/
+
+echo "BUILD_DIR: $BUILD_DIR"
+echo "CACHE_DIR: $CACHE_DIR"
 ### Load dependencies
 
 source $BP_DIR/lib/output.sh
-source $BP_DIR/lib/json.sh
 source $BP_DIR/lib/failure.sh
-source $BP_DIR/lib/environment.sh
-source $BP_DIR/lib/binaries.sh
 source $BP_DIR/lib/cache.sh
-source $BP_DIR/lib/dependencies.sh
+source $BP_DIR/lib/environment.sh
 
 ### Handle errors
 
@@ -37,101 +38,52 @@ handle_failure() {
 }
 trap 'handle_failure' ERR
 
-### Check initial state
-
-[ -e "$BUILD_DIR/node_modules" ] && PREBUILD=true || PREBUILD=false
-
-### Failures that should be caught immediately
-
-fail_invalid_package_json "$BUILD_DIR"
-warn_prebuilt_modules "$BUILD_DIR"
-warn_missing_package_json "$BUILD_DIR"
-
 ### Compile
 
 create_env() {
-  write_profile "$BP_DIR" "$BUILD_DIR"
-  write_export "$BP_DIR" "$BUILD_DIR"
+  # write_profile "$BP_DIR" "$BUILD_DIR"
+  # write_export "$BP_DIR" "$BUILD_DIR"
   export_env_dir "$ENV_DIR"
-  create_default_env
+  create_default_env "$BUILD_DIR"
+  list_assets_config
+  load_dependencies "$ASSETS_DEPS"
+
+  echo PATH
+  echo $PATH
+  echo
 }
 
-header "Creating runtime environment"
+header "Creating Asset environment"
 create_env # can't indent the whole thing because piping causes subshells; no exporting possible
-list_node_config | indent
+# list__config | indent
 
-install_bins() {
-  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
-  local iojs_engine=$(read_json "$BUILD_DIR/package.json" ".engines.iojs")
-  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
-
-  if [ -n "$iojs_engine" ]; then
-    echo "engines.iojs (package.json):  $iojs_engine (iojs)"
-  else
-    echo "engines.node (package.json):  ${node_engine:-unspecified}"
-  fi
-  echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
-  echo ""
-
-  if [ -n "$iojs_engine" ]; then
-    warn_node_engine "$iojs_engine"
-    install_iojs "$iojs_engine" "$BUILD_DIR/.heroku/node"
-  else
-    warn_node_engine "$node_engine"
-    install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
-  fi
-  install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
-  warn_old_npm
-}
-
-header "Installing binaries"
-install_bins | indent
-
-restore_cache() {
-  local cache_status=$(get_cache_status)
-
-  if [ "$cache_status" == "disabled" ]; then
-    echo "Skipping (cache disabled)"
-  elif [ "$cache_status" == "invalidated" ]; then
-    echo "Skipping (cache invalidated)"
-  else
-    local cache_directories=$(get_cache_directories)
-    if [ "$cache_directories" == "" ]; then
-      echo "Loading 1 from cacheDirectories (default):"
-      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
-    else
-      echo "Loading $(echo $cache_directories | wc -w | xargs) from cacheDirectories (package.json):"
-      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
-    fi
-  fi
-}
-
-header "Restoring cache"
-restore_cache | indent
-
-build_dependencies() {
-  if $PREBUILD; then
-    echo "Prebuild detected (node_modules already exists)"
-    rebuild_node_modules "$BUILD_DIR"
-  else
-    install_node_modules "$BUILD_DIR"
-  fi
-}
-
-header "Building dependencies"
-build_dependencies | indent
+# restore_cache() {
+#   echo 'create_signature': "$(create_signature)"
+#   echo 'load_signature': "$(load_signature)"
+#
+#   local cache_status=$(get_cache_status)
+#
+#   if [ "$cache_status" == "disabled" ]; then
+#     echo "Skipping (cache disabled)"
+#     compile_assets
+#   elif [ "$cache_status" == "invalidated" ]; then
+#     echo "Skipping (cache invalidated)"
+#     compile_assets
+#   else
+#     echo "Loading 1 from cacheDirectories (default):"
+#     restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$ASSETS_CACHE_DIRECTORY"
+#   fi
+# }
+#
+# header "Restoring cache"
+# restore_cache | indent
+compile_assets
 
 cache_build() {
-  local cache_directories=$(get_cache_directories)
-  echo "Clearing previous node cache"
+  echo "Clearing previous assets cache"
   clear_cache
-  if [ "$cache_directories" == "" ]; then
-    echo "Saving 1 cacheDirectories (default):"
-    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "node_modules"
-  else
-    echo "Saving $(echo $cache_directories | wc -w | xargs) cacheDirectories (package.json):"
-    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
-  fi
+  echo "Saving 1 cacheDirectories (default):"
+  save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$ASSETS_CACHE_DIRECTORY"
 }
 
 header "Caching build"
@@ -139,7 +91,7 @@ cache_build | indent
 
 summarize_build() {
   cd $BUILD_DIR
-  (npm ls --depth=0 | tail -n +2 || true) 2>/dev/null
+  (ls -llh _public || true) 2>/dev/null
 }
 
 header "Build succeeded!"
